spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/l2calc
    username: l2calc_user
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
